export const RESPONSE_SUCCESS_CODE = 0;

export const HANDLER_IDS = {
  INITIAL: 0,
  JOIN_LOBBY : 1,
  CREAT_ROOM : 2,
  JOIN_ROOM : 3,
  GAME_READY : 4,
  UPDATE_LOCATION: 5,
  CARRY_UPDATE : 6,
  ROOM_DATA : 7,
  CHANGEROLE : 8,
};